language: node_js
node_js:
    - "node"
branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
cache:
    directories:
    - "node_modules"
before_script:
    - npm install
script:
    - npm run webpack:prod
    - npm run kss:prod
    - cp dest/styles.css docs/styles.css
    - tar -zcvf style_pack.tar.gz dest/
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    local_dir: "docs"
    on:
        branch: master
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: "style_pack.tar.gz"
    skip_cleanup: true
    on:
        tags: true
